export const ProjectContext = {
  email: '',
  setEmail: () => {},
  username: '',
  setUserName: () => {},
  fistname: '',
  setFirstname: () => {},
  lastname: '',
  setLastname: () => {},
  password: '',
  setPassword: () => {},
  currentUser: {},
  getUserInfomation: () => {},
  placeSaved: [],
  getPlaceSaved: () => {},
  loading: true,
  setLoading: () => {},
};
