export const ProjectContext = {
  email: '',
  setEmail: () => {},
  username: '',
  setUserName: () => {},
  fistname: '',
  setFirstname: () => {},
  lastname: '',
  setLastname: () => {},
  password: '',
  setPassword: () => {},
  currentUser: {},
  getUserInfomation: () => {},
  placeSaved: [],
  getPlaceSaved: () => {},
  loading: true,
  setLoading: () => {},
  placeImg: '',
  setPlaceImg: () => {},
  placeName: '',
  setPlaceName: () => {},
  placeAddress: '',
  setPlaceAddress: () => {},
  placeLongitude: 0,
  setPlaceLongitude: () => {},
  placeLatitude: 0,
  setPlaceLatitude: () => {},
  coords: {},
  setCoords: () => {},
  currentCoords: {},
  setCurrentCoords: () => {},
  handleRemovePlace: () => {},
};
